<<<<<<< HEAD
# Generated by Django 2.2.5 on 2019-09-13 13:39
=======
# Generated by Django 2.2.5 on 2019-09-14 07:29
>>>>>>> 1b5ea090da4f12f49202c2e801fd4e471efc843a

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
